# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 036ac1081b539eedf6731548db3cd084c8369080391232a31f061d50f16652a54ed55ba17408ecae68040175a175f8024bc2374a7044ea557d55dfebd5d6a700

test:
  secret_key_base: a2d6bbf50ff56d1beaea9a9928f4d305348ff79c3271d4ee674d7f18bb253e13d3bf44a8b57be3df1485f64ab339dcbba62d06a5d408afec28fff95191052672

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
